sonar.projectKey=Zen0x7_ODTE
sonar.organization=zen0x7

sonar.sources=src,include
sonar.tests=tests
sonar.exclusions=third_party/**,build/**

sonar.sourceEncoding=UTF-8
sonar.cfamily.build-wrapper-output=build-wrapper-output.json
sonar.coverageReportPaths=build/coverage.xml
